import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import dynamic from 'next/dynamic'
const Navbar = dynamic(() => import('../components/Navbar'), {
  ssr:false,
})
 
const Main = dynamic(() => import('../components/Main'), {
  ssr:false,
})
 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [accounts,setAccounts]=useState([])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='overlay'>
        <div className='app'>
        <Navbar accounts={accounts} setAccounts={setAccounts}/>
      <Main accounts={accounts} setAccounts={setAccounts}/>
        </div>
        <div className='moving' >

        </div>
      </div>


     
    </>
  )
}
